model = "gpt-5-codex"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[projects."/Users/wake_yuki/dev/almondo/pj_ttdc_system_phase5"]
trust_level = "trusted"

[projects."/Users/wake_yuki/dev/almondo/pj_leadcreate_assessmentsystem_phase2"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

# [mcp_servers.github]
# command = "mcp-proxy"
# args = [
# 	"--transport",
# 	"streamablehttp",
# 	"-H",
# 	"Authorization",
# 	"Bearer 取得したGitHubのPAT",
# 	"https://api.githubcopilot.com/mcp/",
# ]

# [mcp_servers.sequential-thinking]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.spec-workflow]
command = "npx"
args = ["-y", "@pimzino/spec-workflow-mcp@latest", "/Users/wake_yuki/dev/almondo/pj_ttdc_system_phase5/app"]
# args = ["-y", "@pimzino/spec-workflow-mcp@latest", "/Users/wake_yuki/dev/almondo/pj_leadcreate_assessmentsystem_phase2/"]
